// Package accounts contains the CloudForge Accounts API REST layer.
//
// # Layers
//
// This package is the REST API layer. It contains:
//   - Handler            — implements generated.StrictServerInterface (transport only)
//   - NewRouter()        — wires the generated mux with the shared middleware chain
//   - models.go          — HTTP-only request/response model aliases
//   - models_transform.go — REST <-> service layer mapping functions
//   - errors.go          — typed REST errors and mapping from service errors
//
// The service layer lives in [accounts/service]. Generated types live in
// [accounts/generated] (never hand-edited).
//
// # Routing
//
// Routes are registered on a plain [http.ServeMux] using Go 1.22+ method+path
// patterns generated by oapi-codegen's "std-http-server" target.
//
// # Middleware chain
//
//	RequestID → StructuredLogger → OTelSpan → Metrics → TenantContext → PanicRecovery
//
// # Wire-up
//
//	svc := service.New(service.Deps{...})
//	h   := accounts.NewHandler(svc, logger)
//	router := accounts.NewRouter(h, logger, reg, "accounts_svc")
//	http.ListenAndServe(":8082", router)
package accounts

import (
	"encoding/json"
	"log/slog"
	"net/http"

	"github.com/prometheus/client_golang/prometheus"

	"github.com/jtomasevic/cloud-forge/internal/metrics"
	"github.com/jtomasevic/cloud-forge/internal/middleware"
	"github.com/jtomasevic/cloud-forge/services/accounts/generated"
)

// NewRouter builds the accounts HTTP router.
//
// It wires the generated StrictServerInterface adapter to a plain
// [http.ServeMux], wraps the mux with the shared CloudForge middleware chain,
// and returns the fully composed [http.Handler] ready to be served.
func NewRouter(
	h *Handler,
	logger *slog.Logger,
	reg *prometheus.Registry,
	svcName string,
) http.Handler {
	// ── 1. Generated mux ─────────────────────────────────────────────────────
	mux := generated.HandlerWithOptions(
		generated.NewStrictHandler(h, nil),
		generated.StdHTTPServerOptions{
			ErrorHandlerFunc: opapiErrorHandler,
		},
	)

	// ── 2. /healthz liveness / readiness probe ───────────────────────────────
	top := http.NewServeMux()
	top.HandleFunc("GET /healthz", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte(`{"status":"ok"}`))
	})
	top.Handle("/", mux)

	// ── 3. Middleware chain ───────────────────────────────────────────────────
	chain := middleware.Chain(logger, reg, svcName)
	_ = metrics.Handler(reg)

	return chain.Apply(top)
}

// opapiErrorHandler translates oapi-codegen request validation failures into
// the platform's standard JSON error envelope (400 Bad Request).
func opapiErrorHandler(w http.ResponseWriter, _ *http.Request, err error) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusBadRequest)
	_ = json.NewEncoder(w).Encode(BadRequestBody(err.Error()))
}
