// Package storage contains the CloudForge storage service business logic.
//
// # Routing
//
// Routes are registered on a plain [http.ServeMux] using Go 1.22+ method+path
// patterns generated by oapi-codegen's "std-http-server" target. There is no
// third-party router. Path values (e.g. {tenant}, {project}) are read with
// [http.Request.PathValue], consistent with [internal/middleware.TenantContext].
//
// # Middleware chain
//
// The middleware chain from [internal/middleware] is applied on top of the
// generated mux in [NewRouter]:
//
//	RequestID → StructuredLogger → OTelSpan → Metrics → TenantContext → PanicRecovery
//
// # Wire-up
//
// In main.go (or a service bootstrap file), call [NewRouter] with a concrete
// implementation of [generated.StrictServerInterface]:
//
//	handler := storage.NewRouter(storage.NewHandler(), chain, registry, "storage_svc")
//	http.ListenAndServe(":8080", handler)
package storage

import (
	"log/slog"
	"net/http"

	"github.com/prometheus/client_golang/prometheus"

	cferrors "github.com/jtomasevic/cloud-forge/internal/errors"
	"github.com/jtomasevic/cloud-forge/internal/metrics"
	"github.com/jtomasevic/cloud-forge/internal/middleware"
	"github.com/jtomasevic/cloud-forge/services/storage/generated"
)

// NewRouter builds the storage service HTTP router.
//
// It wires the generated [generated.StrictServerInterface] adapter to a plain
// [http.ServeMux], wraps the mux with the shared CloudForge middleware chain,
// and returns the fully composed [http.Handler] ready to be served.
//
// Parameters:
//   - impl    — the business logic implementation of StrictServerInterface
//   - logger  — the service-level structured logger (from internal/logging)
//   - reg     — the Prometheus registry for this service instance
//   - svcName — Prometheus namespace prefix (e.g. "storage_svc")
func NewRouter(
	impl generated.StrictServerInterface,
	logger *slog.Logger,
	reg *prometheus.Registry,
	svcName string,
) http.Handler {
	// ── 1. Create the generated mux ────────────────────────────────────────
	// HandlerWithOptions registers every operation from the OpenAPI spec on a
	// new *http.ServeMux using Go 1.22 METHOD /path/{param} patterns.
	// The ErrorHandlerFunc translates oapi-codegen validation errors into the
	// platform's standard JSON error shape so clients always see the same
	// envelope regardless of which layer rejected the request.
	mux := generated.HandlerWithOptions(
		generated.NewStrictHandler(impl, nil),
		generated.StdHTTPServerOptions{
			// requestErrorHandler fires when oapi-codegen cannot unmarshal or
			// validate the incoming request (e.g. missing required field, wrong type).
			ErrorHandlerFunc: requestErrorHandler,
		},
	)

	// ── 2. Build the middleware chain ───────────────────────────────────────
	// The chain is applied outermost-first: RequestID is the very first
	// middleware to run and PanicRecovery is the innermost safety net.
	chain := middleware.Chain(logger, reg, svcName)

	// ── 3. Wrap the mux with metrics route-pattern annotation ──────────────
	// metrics.WithRoutePattern is applied PER-ROUTE at registration time to
	// provide low-cardinality Prometheus labels (pattern instead of raw path).
	// Here we wrap the entire handler because oapi-codegen registers its own
	// sub-mux; the route pattern label will fall back to the URL path for now.
	// Per-route annotation can be added in a follow-up if higher cardinality
	// control is required.
	_ = metrics.Handler(reg) // register /metrics endpoint separately in main()

	return chain.Apply(mux)
}

// requestErrorHandler translates oapi-codegen request validation failures
// into the platform's standard JSON error envelope (internal/errors.WriteJSON).
//
// This is called when the generated router cannot decode or validate an
// incoming request body before it reaches the handler implementation.
func requestErrorHandler(w http.ResponseWriter, r *http.Request, err error) {
	cferrors.WriteJSON(w, r, cferrors.BadRequest(err.Error()))
}
