// Package accountsclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package accountsclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for AccountStatus.
const (
	AccountStatusACTIVE       AccountStatus = "ACTIVE"
	AccountStatusDELETED      AccountStatus = "DELETED"
	AccountStatusPROVISIONING AccountStatus = "PROVISIONING"
	AccountStatusSUSPENDED    AccountStatus = "SUSPENDED"
)

// Defines values for DeleteAccountAcceptedStatus.
const (
	QUEUED DeleteAccountAcceptedStatus = "QUEUED"
)

// Defines values for ErrorDetailCode.
const (
	BADREQUEST         ErrorDetailCode = "BAD_REQUEST"
	CONFLICT           ErrorDetailCode = "CONFLICT"
	INTERNALERROR      ErrorDetailCode = "INTERNAL_ERROR"
	NOTFOUND           ErrorDetailCode = "NOT_FOUND"
	SERVICEUNAVAILABLE ErrorDetailCode = "SERVICE_UNAVAILABLE"
	UNPROCESSABLE      ErrorDetailCode = "UNPROCESSABLE"
)

// Defines values for IssueKeyResponseStatus.
const (
	IssueKeyResponseStatusACTIVE IssueKeyResponseStatus = "ACTIVE"
)

// Defines values for RegisterRequestPlan.
const (
	Enterprise RegisterRequestPlan = "enterprise"
	Pro        RegisterRequestPlan = "pro"
	Starter    RegisterRequestPlan = "starter"
)

// AccountResponse Full account record including network topology when provisioned.
type AccountResponse struct {
	CreatedAt   time.Time `json:"created_at"`
	DisplayName string    `json:"display_name"`
	Plan        string    `json:"plan"`

	// PodCidr vCluster pod CIDR. Populated once status=ACTIVE.
	PodCidr *string `json:"pod_cidr,omitempty"`

	// ServiceCidr vCluster service CIDR. Populated once status=ACTIVE.
	ServiceCidr *string `json:"service_cidr,omitempty"`

	// Slug URL-safe tenant identifier.
	Slug string `json:"slug"`

	// Status Lifecycle state of a tenant account.
	Status AccountStatus `json:"status"`

	// TenantId Immutable UUID assigned at account creation.
	TenantId openapi_types.UUID `json:"tenant_id"`
}

// AccountStatus Lifecycle state of a tenant account.
type AccountStatus string

// CreateAccountAccepted Returned immediately (202) when network provisioning is accepted.
type CreateAccountAccepted struct {
	// JobId Provisioning job ID. Poll GET /accounts/{slug}/jobs/{job_id}.
	JobId openapi_types.UUID `json:"job_id"`
	Slug  string             `json:"slug"`

	// Status Lifecycle state of a tenant account.
	Status AccountStatus `json:"status"`

	// TenantId UUID of the tenant whose network is being provisioned.
	TenantId openapi_types.UUID `json:"tenant_id"`
}

// DeleteAccountAccepted Returned immediately (202) when account deletion is accepted.
type DeleteAccountAccepted struct {
	// JobId Deprovisioning job ID.
	JobId  openapi_types.UUID          `json:"job_id"`
	Slug   string                      `json:"slug"`
	Status DeleteAccountAcceptedStatus `json:"status"`
}

// DeleteAccountAcceptedStatus defines model for DeleteAccountAccepted.Status.
type DeleteAccountAcceptedStatus string

// ErrorDetail Machine-readable error payload on all non-2xx responses.
type ErrorDetail struct {
	Code      ErrorDetailCode `json:"code"`
	Message   string          `json:"message"`
	RequestId *string         `json:"request_id,omitempty"`
}

// ErrorDetailCode defines model for ErrorDetail.Code.
type ErrorDetailCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Machine-readable error payload on all non-2xx responses.
	Error ErrorDetail `json:"error"`
}

// IssueKeyRequest Request body for issuing a new API key for a tenant.
type IssueKeyRequest struct {
	// DisplayName Human-readable label for the key (e.g. "CI/CD pipeline").
	DisplayName string `json:"display_name"`

	// Scopes Comma-separated permission scopes. Defaults to "provision:read" if omitted.
	Scopes *string `json:"scopes,omitempty"`
}

// IssueKeyResponse Response after issuing a new API key. The raw key is returned ONCE
// in this response and never stored — the caller must persist it.
type IssueKeyResponse struct {
	CreatedAt   time.Time `json:"created_at"`
	DisplayName string    `json:"display_name"`

	// KeyId Stable identifier used for revocation.
	KeyId openapi_types.UUID `json:"key_id"`

	// RawKey The raw bearer token. STORE THIS NOW — it cannot be retrieved again.
	// Use as: Authorization: Bearer <raw_key>
	RawKey string                 `json:"raw_key"`
	Scopes string                 `json:"scopes"`
	Status IssueKeyResponseStatus `json:"status"`
}

// IssueKeyResponseStatus defines model for IssueKeyResponse.Status.
type IssueKeyResponseStatus string

// RegisterRequest Self-service registration request. Creates a user record, opens a
// tenant account, and starts VPC provisioning in one atomic flow.
//
// `email` is the login username — must be a valid RFC-5322 address.
// `password` is accepted in plain text over TLS and immediately bcrypt-
// hashed (cost 12) before storage. The raw password is never logged.
type RegisterRequest struct {
	// DisplayName Human-readable organisation name shown in the UI and logs.
	DisplayName string `json:"display_name"`

	// Email Primary login email and username. Must be unique across the platform.
	// Cannot be changed after registration (use account settings, TBD).
	Email openapi_types.Email `json:"email"`

	// Password Plain-text password. Minimum 8 characters.
	// Bcrypt-hashed (cost 12) at the service layer — never stored raw.
	Password string `json:"password"`

	// Plan Billing plan tier controlling resource quotas.
	Plan RegisterRequestPlan `json:"plan"`

	// Slug Unique URL-safe identifier for the tenant account. Used as the
	// Kubernetes namespace suffix and vCluster name. Immutable after
	// creation.
	Slug string `json:"slug"`
}

// RegisterRequestPlan Billing plan tier controlling resource quotas.
type RegisterRequestPlan string

// RegisterResponse Returned (201 Created) after successful self-service registration.
//
// `initial_api_key` is shown ONCE in this response and never stored in
// plain text. The caller MUST persist it to authenticate future requests.
//
// VPC provisioning is **not** started here. Call
// POST /accounts/{tenant_slug}/provision (authenticated) after
// registration to start the network provisioning workflow.
type RegisterResponse struct {
	// InitialApiKey Bootstrapped API key. STORE THIS NOW — it will not be shown again.
	// Use as: Authorization: Bearer <initial_api_key>
	InitialApiKey string `json:"initial_api_key"`

	// Slug The tenant slug as submitted.
	Slug string `json:"slug"`

	// TenantId UUID assigned to the new tenant account.
	TenantId openapi_types.UUID `json:"tenant_id"`

	// UserId UUID assigned to the newly created user record.
	UserId openapi_types.UUID `json:"user_id"`
}

// KeyIDParam defines model for KeyIDParam.
type KeyIDParam = openapi_types.UUID

// TenantSlugParam defines model for TenantSlugParam.
type TenantSlugParam = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ErrorResponse

// IssueKeyJSONRequestBody defines body for IssueKey for application/json ContentType.
type IssueKeyJSONRequestBody = IssueKeyRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// DeleteAccount request
	DeleteAccount(ctx context.Context, tenantSlug TenantSlugParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAccount request
	GetAccount(ctx context.Context, tenantSlug TenantSlugParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// IssueKeyWithBody request with any body
	IssueKeyWithBody(ctx context.Context, tenantSlug TenantSlugParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	IssueKey(ctx context.Context, tenantSlug TenantSlugParam, body IssueKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RevokeKey request
	RevokeKey(ctx context.Context, tenantSlug TenantSlugParam, keyId KeyIDParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ProvisionNetwork request
	ProvisionNetwork(ctx context.Context, tenantSlug TenantSlugParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RegisterWithBody request with any body
	RegisterWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	Register(ctx context.Context, body RegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) DeleteAccount(ctx context.Context, tenantSlug TenantSlugParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAccountRequest(c.Server, tenantSlug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAccount(ctx context.Context, tenantSlug TenantSlugParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAccountRequest(c.Server, tenantSlug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) IssueKeyWithBody(ctx context.Context, tenantSlug TenantSlugParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewIssueKeyRequestWithBody(c.Server, tenantSlug, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) IssueKey(ctx context.Context, tenantSlug TenantSlugParam, body IssueKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewIssueKeyRequest(c.Server, tenantSlug, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RevokeKey(ctx context.Context, tenantSlug TenantSlugParam, keyId KeyIDParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRevokeKeyRequest(c.Server, tenantSlug, keyId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ProvisionNetwork(ctx context.Context, tenantSlug TenantSlugParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProvisionNetworkRequest(c.Server, tenantSlug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RegisterWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Register(ctx context.Context, body RegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDeleteAccountRequest generates requests for DeleteAccount
func NewDeleteAccountRequest(server string, tenantSlug TenantSlugParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "tenant_slug", runtime.ParamLocationPath, tenantSlug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/accounts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAccountRequest generates requests for GetAccount
func NewGetAccountRequest(server string, tenantSlug TenantSlugParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "tenant_slug", runtime.ParamLocationPath, tenantSlug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/accounts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewIssueKeyRequest calls the generic IssueKey builder with application/json body
func NewIssueKeyRequest(server string, tenantSlug TenantSlugParam, body IssueKeyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewIssueKeyRequestWithBody(server, tenantSlug, "application/json", bodyReader)
}

// NewIssueKeyRequestWithBody generates requests for IssueKey with any type of body
func NewIssueKeyRequestWithBody(server string, tenantSlug TenantSlugParam, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "tenant_slug", runtime.ParamLocationPath, tenantSlug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/accounts/%s/keys", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRevokeKeyRequest generates requests for RevokeKey
func NewRevokeKeyRequest(server string, tenantSlug TenantSlugParam, keyId KeyIDParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "tenant_slug", runtime.ParamLocationPath, tenantSlug)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "key_id", runtime.ParamLocationPath, keyId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/accounts/%s/keys/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewProvisionNetworkRequest generates requests for ProvisionNetwork
func NewProvisionNetworkRequest(server string, tenantSlug TenantSlugParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "tenant_slug", runtime.ParamLocationPath, tenantSlug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/accounts/%s/provision", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRegisterRequest calls the generic Register builder with application/json body
func NewRegisterRequest(server string, body RegisterJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRegisterRequestWithBody(server, "application/json", bodyReader)
}

// NewRegisterRequestWithBody generates requests for Register with any type of body
func NewRegisterRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/register")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// DeleteAccountWithResponse request
	DeleteAccountWithResponse(ctx context.Context, tenantSlug TenantSlugParam, reqEditors ...RequestEditorFn) (*DeleteAccountHTTPResponse, error)

	// GetAccountWithResponse request
	GetAccountWithResponse(ctx context.Context, tenantSlug TenantSlugParam, reqEditors ...RequestEditorFn) (*GetAccountHTTPResponse, error)

	// IssueKeyWithBodyWithResponse request with any body
	IssueKeyWithBodyWithResponse(ctx context.Context, tenantSlug TenantSlugParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*IssueKeyHTTPResponse, error)

	IssueKeyWithResponse(ctx context.Context, tenantSlug TenantSlugParam, body IssueKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*IssueKeyHTTPResponse, error)

	// RevokeKeyWithResponse request
	RevokeKeyWithResponse(ctx context.Context, tenantSlug TenantSlugParam, keyId KeyIDParam, reqEditors ...RequestEditorFn) (*RevokeKeyHTTPResponse, error)

	// ProvisionNetworkWithResponse request
	ProvisionNetworkWithResponse(ctx context.Context, tenantSlug TenantSlugParam, reqEditors ...RequestEditorFn) (*ProvisionNetworkHTTPResponse, error)

	// RegisterWithBodyWithResponse request with any body
	RegisterWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterHTTPResponse, error)

	RegisterWithResponse(ctx context.Context, body RegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterHTTPResponse, error)
}

type DeleteAccountHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *DeleteAccountAccepted
	JSON400      *BadRequest
	JSON404      *NotFound
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r DeleteAccountHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAccountHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAccountHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AccountResponse
	JSON400      *BadRequest
	JSON404      *NotFound
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r GetAccountHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAccountHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type IssueKeyHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *IssueKeyResponse
	JSON400      *BadRequest
	JSON404      *NotFound
	JSON422      *UnprocessableEntity
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r IssueKeyHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r IssueKeyHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RevokeKeyHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *BadRequest
	JSON404      *NotFound
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r RevokeKeyHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RevokeKeyHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ProvisionNetworkHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *CreateAccountAccepted
	JSON400      *BadRequest
	JSON404      *NotFound
	JSON409      *Conflict
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r ProvisionNetworkHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ProvisionNetworkHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RegisterHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *RegisterResponse
	JSON400      *BadRequest
	JSON409      *ErrorResponse
	JSON422      *UnprocessableEntity
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r RegisterHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RegisterHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// DeleteAccountWithResponse request returning *DeleteAccountHTTPResponse
func (c *ClientWithResponses) DeleteAccountWithResponse(ctx context.Context, tenantSlug TenantSlugParam, reqEditors ...RequestEditorFn) (*DeleteAccountHTTPResponse, error) {
	rsp, err := c.DeleteAccount(ctx, tenantSlug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAccountHTTPResponse(rsp)
}

// GetAccountWithResponse request returning *GetAccountHTTPResponse
func (c *ClientWithResponses) GetAccountWithResponse(ctx context.Context, tenantSlug TenantSlugParam, reqEditors ...RequestEditorFn) (*GetAccountHTTPResponse, error) {
	rsp, err := c.GetAccount(ctx, tenantSlug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAccountHTTPResponse(rsp)
}

// IssueKeyWithBodyWithResponse request with arbitrary body returning *IssueKeyHTTPResponse
func (c *ClientWithResponses) IssueKeyWithBodyWithResponse(ctx context.Context, tenantSlug TenantSlugParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*IssueKeyHTTPResponse, error) {
	rsp, err := c.IssueKeyWithBody(ctx, tenantSlug, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseIssueKeyHTTPResponse(rsp)
}

func (c *ClientWithResponses) IssueKeyWithResponse(ctx context.Context, tenantSlug TenantSlugParam, body IssueKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*IssueKeyHTTPResponse, error) {
	rsp, err := c.IssueKey(ctx, tenantSlug, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseIssueKeyHTTPResponse(rsp)
}

// RevokeKeyWithResponse request returning *RevokeKeyHTTPResponse
func (c *ClientWithResponses) RevokeKeyWithResponse(ctx context.Context, tenantSlug TenantSlugParam, keyId KeyIDParam, reqEditors ...RequestEditorFn) (*RevokeKeyHTTPResponse, error) {
	rsp, err := c.RevokeKey(ctx, tenantSlug, keyId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRevokeKeyHTTPResponse(rsp)
}

// ProvisionNetworkWithResponse request returning *ProvisionNetworkHTTPResponse
func (c *ClientWithResponses) ProvisionNetworkWithResponse(ctx context.Context, tenantSlug TenantSlugParam, reqEditors ...RequestEditorFn) (*ProvisionNetworkHTTPResponse, error) {
	rsp, err := c.ProvisionNetwork(ctx, tenantSlug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProvisionNetworkHTTPResponse(rsp)
}

// RegisterWithBodyWithResponse request with arbitrary body returning *RegisterHTTPResponse
func (c *ClientWithResponses) RegisterWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterHTTPResponse, error) {
	rsp, err := c.RegisterWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterHTTPResponse(rsp)
}

func (c *ClientWithResponses) RegisterWithResponse(ctx context.Context, body RegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterHTTPResponse, error) {
	rsp, err := c.Register(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterHTTPResponse(rsp)
}

// ParseDeleteAccountHTTPResponse parses an HTTP response from a DeleteAccountWithResponse call
func ParseDeleteAccountHTTPResponse(rsp *http.Response) (*DeleteAccountHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAccountHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest DeleteAccountAccepted
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAccountHTTPResponse parses an HTTP response from a GetAccountWithResponse call
func ParseGetAccountHTTPResponse(rsp *http.Response) (*GetAccountHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAccountHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AccountResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseIssueKeyHTTPResponse parses an HTTP response from a IssueKeyWithResponse call
func ParseIssueKeyHTTPResponse(rsp *http.Response) (*IssueKeyHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &IssueKeyHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest IssueKeyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest UnprocessableEntity
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseRevokeKeyHTTPResponse parses an HTTP response from a RevokeKeyWithResponse call
func ParseRevokeKeyHTTPResponse(rsp *http.Response) (*RevokeKeyHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RevokeKeyHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseProvisionNetworkHTTPResponse parses an HTTP response from a ProvisionNetworkWithResponse call
func ParseProvisionNetworkHTTPResponse(rsp *http.Response) (*ProvisionNetworkHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ProvisionNetworkHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest CreateAccountAccepted
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseRegisterHTTPResponse parses an HTTP response from a RegisterWithResponse call
func ParseRegisterHTTPResponse(rsp *http.Response) (*RegisterHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RegisterHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest RegisterResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest UnprocessableEntity
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
