// Package provisioner contains the CloudForge VPC provisioner service's
// REST API layer.
//
// # Layers
//
// This package is the REST API layer. It contains:
//   - Handler      — implements generated.StrictServerInterface (transport only)
//   - NewRouter()  — wires the generated mux with the shared middleware chain
//   - models.go    — HTTP-only request/response models
//   - models_transform.go — REST <-> service layer mapping functions
//   - errors.go    — typed REST errors and mapping from service errors
//
// The service layer lives in [provisioner/service]. The generated types and
// HTTP stubs live in [provisioner/generated] (never hand-edited).
//
// # Routing
//
// Routes are registered on a plain [http.ServeMux] using Go 1.22+ method+path
// patterns generated by oapi-codegen's "std-http-server" target. No third-party
// router is used.
//
// # Middleware chain
//
//	RequestID → StructuredLogger → OTelSpan → Metrics → TenantContext → PanicRecovery
//
// # Wire-up
//
//	svc := service.New(service.Deps{...})
//	handler := provisioner.NewRouter(provisioner.NewHandler(svc), logger, reg, "provisioner_svc")
//	http.ListenAndServe(":8080", handler)
package provisioner

import (
	"encoding/json"
	"log/slog"
	"net/http"

	"github.com/prometheus/client_golang/prometheus"

	"github.com/jtomasevic/cloud-forge/internal/metrics"
	"github.com/jtomasevic/cloud-forge/internal/middleware"
	"github.com/jtomasevic/cloud-forge/services/provisioner/generated"
)

// NewRouter builds the provisioner HTTP router.
//
// It wires the generated StrictServerInterface adapter to a plain
// [http.ServeMux], wraps the mux with the shared CloudForge middleware chain,
// and returns the fully composed [http.Handler] ready to be served.
//
// Parameters:
//   - h       — the Handler implementation of generated.StrictServerInterface
//   - logger  — the service-level structured logger
//   - reg     — the Prometheus registry for this service instance
//   - svcName — Prometheus namespace prefix (e.g. "provisioner_svc")
func NewRouter(
	h *Handler,
	logger *slog.Logger,
	reg *prometheus.Registry,
	svcName string,
) http.Handler {
	// ── 1. Create the generated mux ─────────────────────────────────────────
	// HandlerWithOptions registers every operation on a *http.ServeMux using
	// Go 1.22 METHOD /path/{param} patterns. ErrorHandlerFunc fires when
	// oapi-codegen cannot unmarshal or validate the request before it reaches
	// the handler — we translate that into the platform error envelope.
	mux := generated.HandlerWithOptions(
		generated.NewStrictHandler(h, nil),
		generated.StdHTTPServerOptions{
			ErrorHandlerFunc: opapiErrorHandler,
		},
	)

	// ── 2. Add the /healthz liveness/readiness probe ────────────────────────
	// The Kubernetes Deployment's readinessProbe and livenessProbe both hit
	// GET /healthz.  We handle it on a plain ServeMux before applying the
	// middleware chain so it is lightweight and never counted in business metrics.
	top := http.NewServeMux()
	top.HandleFunc("GET /healthz", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte(`{"status":"ok"}`))
	})
	// Fall through all other paths to the generated API mux.
	top.Handle("/", mux)

	// ── 3. Build and apply the middleware chain ──────────────────────────────
	chain := middleware.Chain(logger, reg, svcName)

	// Register /metrics on the registry; actual scrape endpoint is wired in main.
	_ = metrics.Handler(reg)

	return chain.Apply(top)
}

// opapiErrorHandler translates oapi-codegen request validation failures
// (e.g. missing required field, wrong type, pattern mismatch) into the
// platform's standard JSON error envelope.
func opapiErrorHandler(w http.ResponseWriter, _ *http.Request, err error) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusBadRequest)
	_ = json.NewEncoder(w).Encode(BadRequestBody(err.Error()))
}
