// Package provisioner contains the CloudForge VPC provisioner service's
// REST API layer.
//
// # Layers
//
// This package is the REST API layer. It contains:
//   - Handler      — implements generated.StrictServerInterface (transport only)
//   - NewRouter()  — wires the generated mux with the shared middleware chain
//   - models.go    — HTTP-only request/response models
//   - models_transform.go — REST <-> service layer mapping functions
//   - errors.go    — typed REST errors and mapping from service errors
//
// The service layer lives in [provisioner/service]. The generated types and
// HTTP stubs live in [provisioner/generated] (never hand-edited).
//
// # Routing
//
// Routes are registered on a plain [http.ServeMux] using Go 1.22+ method+path
// patterns generated by oapi-codegen's "std-http-server" target. No third-party
// router is used.
//
// # Middleware chain
//
//	RequestID → StructuredLogger → OTelSpan → Metrics → TenantContext → PanicRecovery
//
// # Wire-up
//
//	svc := service.New(service.Deps{...})
//	handler := provisioner.NewRouter(provisioner.NewHandler(svc), logger, reg, "provisioner_svc")
//	http.ListenAndServe(":8080", handler)
package provisioner

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"os"

	"github.com/prometheus/client_golang/prometheus"

	"github.com/jtomasevic/cloud-forge/internal/metrics"
	"github.com/jtomasevic/cloud-forge/internal/middleware"
	"github.com/jtomasevic/cloud-forge/services/provisioner/generated"
)

// swaggerUIHTML is the single-page Swagger UI template. The two %s placeholders
// are the page title and the URL of the OpenAPI spec respectively.
const swaggerUIHTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>%s</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist/swagger-ui.css"/>
</head>
<body>
<div id="swagger-ui"></div>
<script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist/swagger-ui-bundle.js"></script>
<script>
  SwaggerUIBundle({
    url: "%s",
    dom_id: "#swagger-ui",
    presets: [SwaggerUIBundle.presets.apis, SwaggerUIBundle.SwaggerUIStandalonePreset],
    layout: "BaseLayout",
    deepLinking: true,
  });
</script>
</body>
</html>`

// NewRouter builds the provisioner HTTP router.
//
// It wires the generated StrictServerInterface adapter to a plain
// [http.ServeMux], wraps the mux with the shared CloudForge middleware chain,
// and returns the fully composed [http.Handler] ready to be served.
//
// corsOrigins is the list of origins to allow for CORS (dev only). Pass nil
// to disable CORS headers (production default).
//
// Parameters:
//   - h           — the Handler implementation of generated.StrictServerInterface
//   - logger      — the service-level structured logger
//   - reg         — the Prometheus registry for this service instance
//   - svcName     — Prometheus namespace prefix (e.g. "provisioner_svc")
//   - corsOrigins — dev-only CORS allowed origins; nil disables CORS
func NewRouter(
	h *Handler,
	logger *slog.Logger,
	reg *prometheus.Registry,
	svcName string,
	corsOrigins []string,
) http.Handler {
	// ── 1. Create the generated mux ─────────────────────────────────────────
	mux := generated.HandlerWithOptions(
		generated.NewStrictHandler(h, nil),
		generated.StdHTTPServerOptions{
			ErrorHandlerFunc: opapiErrorHandler,
		},
	)

	// ── 2. Top-level mux: healthz + OpenAPI spec + Swagger UI + API routes ───
	top := http.NewServeMux()

	top.HandleFunc("GET /healthz", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte(`{"status":"ok"}`))
	})

	// Serve the raw OpenAPI YAML spec — consumed by Swagger UI and API clients.
	top.HandleFunc("GET /api/v1/openapi.yaml", func(w http.ResponseWriter, _ *http.Request) {
		spec, err := os.ReadFile("api/provisioner/v1/openapi.yaml")
		if err != nil {
			http.Error(w, "OpenAPI spec not found", http.StatusNotFound)
			return
		}
		w.Header().Set("Content-Type", "application/yaml")
		_, _ = w.Write(spec)
	})

	// Serve a Swagger UI page that loads the spec from the endpoint above.
	top.HandleFunc("GET /api/v1/docs", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		_, _ = fmt.Fprintf(w, swaggerUIHTML, "CloudForge Provisioner API", "/api/v1/openapi.yaml")
	})

	top.Handle("/", mux)

	// ── 3. Build and apply the middleware chain (with optional dev CORS) ─────
	chain := middleware.ChainWithCORS(corsOrigins, logger, reg, svcName)
	_ = metrics.Handler(reg)

	return chain.Apply(top)
}

// opapiErrorHandler translates oapi-codegen request validation failures
// (e.g. missing required field, wrong type, pattern mismatch) into the
// platform's standard JSON error envelope.
func opapiErrorHandler(w http.ResponseWriter, _ *http.Request, err error) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusBadRequest)
	_ = json.NewEncoder(w).Encode(BadRequestBody(err.Error()))
}
